### ISSUE TITLE
Bug in Students-T observations

### ISSUE THREAD

**Issue by mdusilva** [slinderman/ssm#1]
When I run a HMM with Student -T observations i I get the error:

`AttributeError: 'StudentsTObservations' object has no attribute '_log_likelihoods'`

`StudentsTObservations` is inheriting from `_Observations` where `_log_likelihoods` is defined without the underscore `_`.

This only affects 'StudentsTObservations' because other observations define their own `m_step` methods.

**Comment by slinderman** [comment]
Thanks for spotting this, Manuel!  I've fixed it here https://github.com/slinderman/ssm/commit/e5b449ed45c52afa67dfd1fb23b0608f2ed972eb
