### ISSUE TITLE
PoissonObservations sample_x() uses `inv_lambdas`, which does not exist

### ISSUE THREAD

**Issue by eackermann** [slinderman/ssm#10]
See https://github.com/slinderman/ssm/blob/master/ssm/observations.py#L349

I believe this should in fact be `lambdas = np.exp(self.log_lambdas)`

**Comment by slinderman** [comment]
Good catch.  Fixed in https://github.com/slinderman/ssm/commit/163123c06f4203403b54a6ead8a8dccebf281383.
