### ISSUE TITLE
Error is rSLDS notebook

### ISSUE THREAD

**Issue by mafrasiabi** [slinderman/ssm#101]
Hi there,

I was running the notebook for rSLDS model  and i got this error at cell [5]:

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-5-7fcb470c050a> in <module>
     10                                initialize=False, num_iters=100, alpha=0.0)
     11 xhat_lem = q_lem.mean_continuous_states[0]
---> 12 rslds.permute(find_permutation(z, rslds.most_likely_states(xhat_lem, y)))
     13 zhat_lem = rslds.most_likely_states(xhat_lem, y)
     14 

~/Documents/Ylab/Projects/Repos/ssm/ssm/util.py in find_permutation(z1, z2, K1, K2)
     33 
     34     tmp, perm = linear_sum_assignment(-overlap)
---> 35     assert np.all(tmp == np.arange(K1)), "All indices should have been matched!"
     36 
     37     # Pad permutation if K1 < K2

AssertionError: All indices should have been matched!

**Comment by bantin** [comment]
Hi @mafrasiabi, thanks for raising this. I suspect that this is related to #102 . Would you be able to try running the notebook with the latest version of SSM from the `master` branch?

**Comment by mafrasiabi** [comment]
Hi @bantin  , thanks. after running from master branch, it resolved.

**Comment by bantin** [comment]
Thanks!
