### ISSUE TITLE
AutoRegressiveObservations prior on Sigma is too strong for data with small dynamics noise

### ISSUE THREAD

**Issue by slinderman** [slinderman/ssm#102]
In the great refactor of the AR observations model, we bumped up the regularization on the noise covariance.  Josh pointed out that this led to poor parameter estimation and state inference in his simulated data examples.  I think we should revert back to effectively doing MLE by default and expose the hyperparameters of the prior on Sigma in the constructor.  We should also add a little diagonal bias to the covariance before taking the Cholesky decomposition in the Sigmas setter.

**Comment by bantin** [comment]
@slinderman I think we've taken care of this. Okay to close?

**Comment by slinderman** [comment]
Yup, go ahead.
