### ISSUE TITLE
Sampling and Input Driven Transitions

### ISSUE THREAD

**Issue by zashwood** [slinderman/ssm#17]
Hi, 

Thanks for your help with the last issue.  

I modified your Simple HMM notebook to use your input driven transitions class.  There is an issue with the sample function because of the padding that you use in the case where input is not provided.  In particular, if you run:

`T = 100   
K = 2      
D = 1       
M = 3 
true_hmm = HMM(K, D, M, observations="gaussian",transitions = "inputdriven")

input = npr.randn(T, M)

z, y = true_hmm.sample(T, input = input)`

you get an assertion error.

**Comment by slinderman** [comment]
Thanks again, Zoe.  I spent some time trying to clean up the `hmm.sample` code path and document it better.  I also added a test to go through the various combinations of inputs, prefixes, etc and make sure that they at least run for each of the transition and observation models.

See https://github.com/slinderman/ssm/commit/29d8c6ed4aa5c06ed651a98a80be826dd4aa4c16

Let me know if this works for you.
