### ISSUE TITLE
Error when initializing an LDS with autoregressive observations

### ISSUE THREAD

**Issue by davidzoltowski** [slinderman/ssm#20]
I'm getting an error when initializing an LDS with autoregressive observations. For example, this happens when running the notebook "1b Simple Linear Dynamical System" with the relevant lines in cell 6 changed to

```python
# Create the model and initialize its parameters
lds = LDS(N, D, emissions="autoregressive")
lds.initialize(y)
```

The resulting error is
```
ValueError: all the input arrays must have same number of dimensions
```

It looks like the error traces to lines 514-15 in observations.py where there is a zip around a potentially undefined input, although it seems to be more complicated than that.

**Comment by slinderman** [comment]
This was fixed in @bantin's latest commits to master.
