### ISSUE TITLE
Make classes for public API models

### ISSUE THREAD

**Issue by jchutrue** [slinderman/ssm#23]
Currently methods defined in models.py serve as wrappers that return the "private" classes implemented in core.py. It would be nice to have public classes instead of standalone methods. Some example skeleton code:

```
from ssm.core import _HMM
class HMM(_HMM):
    def __init__(self, args):
        # Check that arguments are valid, set up transition & observation
        # models, etc.
        super().__init__(args):
```

That way users such as myself could write subclasses that inherit from the public `HMM` object while implementing additional methods in an application-specific manner. More example skeleton code:

```
from ssm.models import HMM
class CustomHMM(HMM):
    def __init__(self, args):
        # Convert data into format expected by public HMM object,
        # do additional checks, then forward args to superclass
        super().__init__(args)
    
    # Example additional method not implemented either in 
    # public HMM API or private _HMM object
    def fit_ext(self, ext_args):
        # Learn mapping from internal state space to external space
        # e.g. position of animal
```

**Comment by slinderman** [comment]
I've been thinking about the best way to expose the core HMM class.  Maybe the way to do it is to rename the private classes to `BaseHMM`, for example, and make them publicly accessible.  Exposing only the `ssm.models.HMM` function has always been a bit unsatisfying to me, as the name suggests it is a class.

**Comment by slinderman** [comment]
Ok, I've changed the core classes to `BaseHMM`, `BaseHSMM`, `BaseSwitchingLDS`, etc.  You should be able to inherit and extend them as you wish. If you end up adding any functionality that you think would be useful for the base classes, feel free to submit a PR!
