### ISSUE TITLE
NameError when initializing a simple LDS

### ISSUE THREAD

**Issue by erichamc** [slinderman/ssm#25]
Running the following example code: 
`
from ssm.models import LDS
# Set the parameters of the HMM
T = 200    # number of time bins
K = 5       # number of discrete states
D = 2       # number of latent dimensions
N = 10      # number of observed dimensions
# Make an LDS with the somewhat interesting dynamics parameters
true_lds = LDS(N, D, emissions="gaussian")
`
results in the following error:

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-e91a9786f723> in <module>
      8 # Make an LDS with the somewhat interesting dynamics parameters
      9 
---> 10 true_lds = LDS(N, D, emissions="gaussian")

[DIR]/ssm/ssm/models.py in LDS(N, D, M, dynamics, dynamics_kwargs, hierarchical_dynamics_tags, emissions, emission_kwargs, hierarchical_emission_tags, **kwargs)
    393 
    394     # Make the HMM
--> 395     return BaseLDS(N, D, M, dynamics_distn, emission_distn)
    396 
    397 

[DIR]/ssm/ssm/core.py in __init__(self, N, D, M, dynamics, emissions)
   1007         init_state_distn = InitialStateDistribution(1, D, M)
   1008         transitions = StationaryTransitions(1, D, M)
-> 1009         super(_LDS, self).__init__(N, 1, D, M, init_state_distn, transitions, dynamics, emissions)
   1010 
   1011     @ensure_slds_args_not_none

NameError: name '_LDS' is not defined

**Comment by slinderman** [comment]
Thanks for pointing this out. It should be fixed in https://github.com/slinderman/ssm/pull/27 (along with many other improvements to the autoregressive models that the LDS builds upon.
