### ISSUE TITLE
interface to arbitrary data

### ISSUE THREAD

**Issue by kharris** [slinderman/ssm#28]
Hi Scott! I'm going to use your older pyhsmm in the meantime, but it would be great if you could include a natural interface to working with real data. What I mean is, rather than just having your objects built around generating data from a given model and then fitting it, having some kind of sklearn style interface to estimate a model from a timeseries.

Take care,
Kam

**Comment by kharris** [comment]
Maybe my problem is I don't understand the documentation ;-)

**Comment by slinderman** [comment]
Hey Kam,

Glad you found your way to SSM!  Real data examples are on the horizon, don't worry.  In the meantime, my advice would be: take the examples for simulating data and fitting another model to it and strip out the simulating step.  The interface is pretty simple.

```
hmm = HMM(num_states, data_dim, observations="gaussian")
lls = hmm.fit([data_array1, data_array2, ...], method="em")
```

where `data_array1` is a `time x data_dim` array. 

Hope that gets you by for now.  Thanks for your patience while I beef up the docs!

Scott

**Comment by kharris** [comment]
Thanks I see how it works now, cheers. (Doing a comparison with my optimization-based method.)

**Comment by slinderman** [comment]
Great, which part of SSM are you using in particular?  If you come up with some new optimization-based fitting methods let me know -- it'd be great to a) learn about them, and b) incorporate them into the package!
