### ISSUE TITLE
random_rotation

### ISSUE THREAD

**Issue by yahmadian** [slinderman/ssm#38]
Hi Scott, 

Thanks for this great, easy-to-use library!
I may have found a small bug (only relevant for the .initialize methods, as fas as I can see): if you meant the function `random_rotation` in ssm/ssm/util.py to output a random n x n rotation matrix (rotation in n-dim space around a uniformly random axis with small-random or specified angle), then the current function doesn't exactly do that. (Can see this by checking that the determinant of the output matrix is zero, instead of one.) But this can be easily remedied by changing  line 81 from `out = np.zeros((n, n))` to `out = np.eye(n)`. (The current output matrix first projects on the hyperplane perpendicular to the random axis and then rotates the projection in that plane.)

**Comment by slinderman** [comment]
Hi Yashar,

Good catch, and thanks for the easy fix!  I've pushed it in https://github.com/slinderman/ssm/commit/1de11527b57c1b894bf6ccedadafba755c534954

Best,
Scott
