### ISSUE TITLE
Implement an iterative algorithm for MLE in the AR model with correlated Gaussian noise

### ISSUE THREAD

**Issue by slinderman** [slinderman/ssm#42]

**Comment by andrewczgithub** [comment]
hi @slinderman !
Any progress on the above, would be awesome addition to this great library.
Best,
Andrew

**Comment by slinderman** [comment]
Hi @andrewczgithub, I think the current implementation should work just fine, but there are some small changes that could further improve the estimation.  @ahwillia has been thinking about this too.  The next step is to write up a short derivation of the M-step for autoregressive models with correlated noise.  We need to do this anyway for the LDS models, since there we want to maximize the _expected_ log probability under the posterior distribution on continuous latent states.

**Comment by slinderman** [comment]
Update: Spoke with @ahwillia and we convinced ourselves that for the M-step of linear regressions (including linear autoregressive models), the MLE mean estimate does not depend on the covariance, so our two-step procedure should be valid.
