### ISSUE TITLE
Bugs in SLDS (log transition matrices shape error)

### ISSUE THREAD

**Issue by leahwu** [slinderman/ssm#44]
Hi, thanks for this great work in ssm package!

However, when I was running SLDS [notebook](https://github.com/slinderman/ssm/blob/master/notebooks/3%20Switching%20Linear%20Dynamical%20System.ipynb), the code broke down here:
`q_mf_elbos = slds.fit(q_mf, y_masked, masks=mask, num_iters=1000, initialize=False)`.

It threw an Assertion error. After inspecting into the codes,  I found that you have one line commented out in the `StanationaryTransition` class:
``` 
def log_transition_matrices(self, data, input, mask, tag):
    T = data.shape[0]
    log_Ps = self.log_Ps - logsumexp(self.log_Ps, axis=1, keepdims=True)
    # return np.tile(log_Ps[None, :, :], (T-1, 1, 1))
    return log_Ps[None, :, :]
````

This makes the log_Ps has the shape (1,K,K), which does not match the assertion in messages.pyx that it should have the shape (T, K, K).

However, uncommenting the commented line and returning that would fix the issue. But I don't know if this would affect other functions of the package.

**Comment by slinderman** [comment]
Hi @leahwu, 

I think this was a bug introduced by a PR for decreasing memory costs on stationary transition models.   I just merged another (awesome) PR from @davidzoltowski and he updated all of the SLDS examples.  I believe we've fixed that bug too.  Could you give the example notebooks another shot?

**Comment by slinderman** [comment]
Closing as I think this issue is now fixed.
