### ISSUE TITLE
Early stopping?

### ISSUE THREAD

**Issue by jmarkow** [slinderman/ssm#5]
Poking around and I'm not sure if this is already supported, but I was wondering if I could use a fit method like so,

```python
train_data, test_data = split(all_the_data)
hmm = HMM(25, 50, observations='gaussian')
hmm_lls = hmm.fit(train_data, method='em', num_em_iters=200, verbose=True, test_data=test_data)
```

And have the `fit` method compute the test likelihood on test_data to stop the fit once we no longer get improvements in the test likelihood. [See the section from xgboost on early stopping as an example](https://xgboost.readthedocs.io/en/latest/python/python_intro.html).  At the very least, would save some time.

**Comment by slinderman** [comment]
This feature was added in a big commit: https://github.com/slinderman/ssm/commit/38417e5fd33a5926943205b4d49340f31199d7e3
