### ISSUE TITLE
Numerical stability?

### ISSUE THREAD

**Issue by ShawnGeller** [slinderman/ssm#52]
Thank you for building this great package. 

I have more of a question rather than an issue:
It's stated in [Rabiner's review on hidden markov models](https://www.cs.cmu.edu/~cga/behavior/rabiner1.pdf) that the naive forward-backward message passing algorithms are numerically unstable, are you able to avoid this problem just by taking logs first?

**Comment by slinderman** [comment]
That's right, the naive message passing algorithms compute in probability space, and products of probabilities can go to zero very quickly.  We're working in log probability space, which incurs a bit of extra cost but gives numerical stability.   I should also note that there are algorithms that work in probability space but renormalize the messages at each step.  These would probably also suffice, and might be a tad bit faster, but I haven't implemented them.

**Comment by ShawnGeller** [comment]
Thank you for the clarification!
