### ISSUE TITLE
small bug in emissions.py

### ISSUE THREAD

**Issue by themattinthehatt** [slinderman/ssm#53]
Hey @slinderman, there's a tiny bug in the `permute` function of the `_OrthogonalLinearEmissions` class on line 268 of `emissions.py`:

```
self._Ms = self._Bs[perm]
```

should be

```
self._Ms = self._Ms[perm]
```

This is obviously an easy fix; do you have preferred way for me to address small bugs like this in the future? (i.e. through a pull request? I've never done those before)

**Comment by slinderman** [comment]
Thanks Matt! Fixed here https://github.com/slinderman/ssm/commit/0150fc45c768eeb6728087041c4572e089ece53a

I'm going to work on a "Contributors Guide" with instructions on how to do that.  I think the Github preferred way is via a PR, but that involves making a fork, editing it, and submitting a PR.  I think you can do all of this via the web, but it is a bit roundabout.  Stay tuned for more instructions on that, but in the meantime this is fine.

**Comment by slinderman** [comment]
FYI: Check out this approach for making little changes like this one: https://help.github.com/en/articles/editing-files-in-another-users-repository

**Comment by themattinthehatt** [comment]
oh yes, that's super straightforward!
