### ISSUE TITLE
Alternatives to autograd

### ISSUE THREAD

**Issue by hanyas** [slinderman/ssm#55]
This is not a real issue. I am just wondering if you are considering alternatives given that Autograd is not being developed anymore. I've seen the JAX branch, but I'm guessing you are not yet willing to make that move yet. 

I am raising this point in part also because I've noticed how slow Autograd can be in comparison to alternatives like PyTorch. Especially when using NeuralRecurrentTransitions, diffing through the NN seems to be the main bottleneck, at least in my use case. 

I was able to achieve multiple fold speed increase by moving that part of code into PyTorch, although I can see that PyTorch is an overkill and may kill the flexibility of the framework.

**Comment by slinderman** [comment]
Hi @hanyas, 

Yes, I'm looking forward to bringing in JAX as an Autograd replacement.  I love PyTorch and Pyro, but I think JAX will be a more direct replacement for Autograd.  In fact, we'll have a part-time developer coming on board soon and making the Autograd->JAX transition will be a top priority.

Please stay tuned for more updates soon!

Scott
