### ISSUE TITLE
M-step update for sticky transitions

### ISSUE THREAD

**Issue by zashwood** [slinderman/ssm#63]
Hi Scott,

It was great meeting you at SfN.  Once again: we are massive fans of ssm, so I want to thank you and everyone who has worked on it for producing such a nice code base.  

I wanted to ask if the m-step update for the sticky transitions is correct if your alpha parameter != 1.  In particular, I just went through the math, and believe I got a different update (where I am using alpha now to be the Dirichlet distribution parameters):
<img width="760" alt="Screen Shot 2019-11-08 at 2 40 47 PM" src="https://user-images.githubusercontent.com/31960947/68511256-8b382b80-0243-11ea-9567-b2a90f6521ea.png">

Specifically, I think the M-Step for the Sticky transitions should be:
```    def m_step(self, expectations, datas, inputs, masks, tags, **kwargs):
        expected_joints = sum([np.sum(Ezzp1, axis=0) for _, Ezzp1, _ in expectations]) + 1e-8
        expected_joints += self.kappa * np.eye(self.K) + (self.alpha-1) * np.ones((self.K, self.K))
        P = expected_joints / expected_joints.sum(axis=1, keepdims=True)
        self.log_Ps = np.log(P)

**Comment by slinderman** [comment]
Good catch, Zoe! I must have been too hasty with that implementation. Do you mind submitting a pull request with the fix? 

Best,
Scott

**Comment by zashwood** [comment]
Hi Scott, of course!  Should just have submitted it :-)

**Comment by slinderman** [comment]
Closing now that PR https://github.com/slinderman/ssm/pull/64 is merged
