### ISSUE TITLE
HSMM example fails

### ISSUE THREAD

**Issue by ktrapeznikov** [slinderman/ssm#79]
need to change the following

https://github.com/slinderman/ssm/blob/855aaad95efa90c5c3b967aa91f2ccaed0187235/ssm/hmm.py#L622

to

```
pi0 = self.init_state_distn.initial_state_distn(data, input, mask, tag)
```

and

here

https://github.com/slinderman/ssm/blob/855aaad95efa90c5c3b967aa91f2ccaed0187235/examples/hsmm.py#L31

`num_em_iters` -> `num_iters`

**Comment by bantin** [comment]
@ktrapeznikov Thanks for pointing this out! I think the first issue was addressed in a prior commit. I just pushed a commit to master address the second issue in `hsmm.py`.
