### ISSUE TITLE
HMM.filter fails after switch to Numba

### ISSUE THREAD

**Issue by bantin** [slinderman/ssm#82]
Trying to call `HMM.filter` gives an error because Numba is not able to work in Nopython mode.

```
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-9-ffcb976fe52f> in <module>
      1 # get a random reach
      2 test_trial_spikes = np.random.choice(train_datas)
----> 3 posterior = simple_hmm.filter(test_trial_spikes)

/Users/bantin/Documents/Linderman-Shenoy/ssm/ssm/util.py in wrapper(self, data, input, mask, tag, **kwargs)
    155 
    156         mask = np.ones_like(data, dtype=bool) if mask is None else mask
--> 157         return f(self, data, input=input, mask=mask, tag=tag, **kwargs)
    158     return wrapper
    159 

/Users/bantin/Documents/Linderman-Shenoy/ssm/ssm/hmm.py in filter(self, data, input, mask, tag)
    264         Ps = self.transitions.transition_matrices(data, input, mask, tag)
    265         log_likes = self.observations.log_likelihoods(data, input, mask, tag)
--> 266         return hmm_filter(pi0, Ps, log_likes)
    267 
    268     @ensure_args_not_none

~/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    374                 e.patch_message(msg)
    375 
--> 376             error_rewrite(e, 'typing')
    377         except errors.UnsupportedError as e:
    378             # Something unsupported is present in the user code, add help info

~/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py in error_rewrite(e, issue_type)
    341                 raise e
    342             else:
--> 343                 reraise(type(e), e, None)
    344 
    345         argtypes = []

~/anaconda3/lib/python3.7/site-packages/numba/six.py in reraise(tp, value, tb)
    656             value = tp()
    657         if value.__traceback__ is not tb:
--> 658             raise value.with_traceback(tb)
    659         raise value
    660 

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Internal error at <numba.typeinfer.CallConstraint object at 0x7fde6b4fb990>.
got an unexpected keyword argument 'axis'
[1] During: resolving callee type: type(CPUDispatcher(<function logsumexp at 0x7fde90a72830>))
[2] During: typing of call at /Users/bantin/Documents/Linderman-Shenoy/ssm/ssm/messages.py (75)

Enable logging at debug level for details.

File "../ssm/messages.py", line 75:
def hmm_filter(pi0, Ps, ll):
    <source elided>
    # Predict forward with the transition matrix
    pz_tt = np.exp(alphas - logsumexp(alphas, axis=1, keepdims=True))
    ^

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/latest/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new
```

I will look into this. We should also beef up the regression tests to avoid this in the future.

**Comment by bantin** [comment]
@slinderman Looks like it's because scipy.special.logsumexp can't be called in nopyton mode (it's not a numpy function which numba knows how to compile). 

I'd propose either
a) writing our own numba-fied version of logsumexp (which can be done in a few lines of code)
b) Getting rid of the @numba.jit decorator for the hmm_filter function, since none of the operations in it will really be sped up by Numba anyway.

My preference would be for (b), but either should be okay.

**Comment by slinderman** [comment]
I'm confused, isn't this calling the `logsumexp` function already defined in messages.py? https://github.com/slinderman/ssm/blob/master/ssm/messages.py#L15

**Comment by bantin** [comment]
@slinderman Ah my bad -- totally missed that! Yes we already have our own version of logsumexp, but it doesn't support the axis and keepdims arguments. I think also there might be a typing issue going on.

**Comment by bantin** [comment]
@slinderman Creating a numba-fied version of logsumexp that accepts an "axis" argument is a bit tricky, because Numba does not support using an `axis` argument with np.max.

See discussion here:
https://github.com/numba/numba/issues/1269

We can write a numba function that applies a supplied function along an axis (as someone has put in the comments of the github issue above), but it gets a little ugly, and might not be worth the trouble. Thoughts?

**Comment by slinderman** [comment]
No need to write our own logsumexp.  Let's just write a for loop,
```
for t in range(T):
    m = np.max(alphas[t])
    pz_tt[t] = np.exp(alphas[t] - m)
    pz_tt[t] /= np.sum(pz_tt[t])
```

**Comment by bantin** [comment]
Agreed, this is much cleaner. This will all be fine when we move to Jax anyway, since they support it! 
https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.max.html

**Comment by bantin** [comment]
@slinderman  Tentative fix here: https://github.com/slinderman/ssm/commit/1423de8cc9f3f8e970f9dfb0bfff99cb53eff131

Numba doesn't allow calling np.dot with 3D arrays, so I moved the matrix multiply into the for-loop as well.

One issue currently is that it generates a warning from Numba:

> NumbaPerformanceWarning: np.dot() is faster on contiguous arrays, called on (array(float64, 1d, C), array(float64, 2d, A))

I'll poke around tomorrow to see if we can get around this by being more clever about the indexing. If not, I'll try to squash the warning.

**Comment by bantin** [comment]
PR is here: #83
